[theme]
base = "dark"
primaryColor = "#537437"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[client]
toolbarMode = "viewer"
showErrorDetails = "none"
showSidebarNavigation = false